#EJEMPLO DE TRES CALIFICCIONES 
#DULCE MARIA TREJO Santos
#variables 
#funciones 
#operacion 
#imprimir resultado, mandar mensaje 

#funcioin con parametro 
def calcular_tres_calificaciones(calif1,calif2,calif3):
   return calif1+calif2+calif3/3


calif1=float(input("ingresa calificacion 1:"))
calif2=float(input("ingresa la calificacion 2:"))
calif3=float(input("ingresa calificacion 3:"))
promedio=calif1+calif2+calif3/3
print("el promedio es:",promedio)
print("la calificacion mas alta es",max(calif1,calif2,calif3))
print("la calificacion mas alta es",min(calif1,calif2,calif3))










































  
  
     
